[google_service_account]
type = "service_account"
project_id = "adta5240f248wjgt"
private_key_id = "e6d89f08f9c9a96a02a9a01f29b85164999561b"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASC...
...rest of your private key...
-----END PRIVATE KEY-----"""
client_email = "streamlit-dock-audit@adta5240f248wjgt.iam.gserviceaccount.com"
client_id = "105601661484535743000"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-dock-audit%40adta5240f248wjgt.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[SHEETS]
SHEET_ID = "1Jca0ZJY0QLq6ZJ623O7FLXrMZwJMFpktomfF2QfA5tI"
TAB_NAME = "Sheet1"
