[gcp_service_account]
type = "service_account"
project_id = "adta5240f248wjgt"
private_key_id = "72d2ff96830e1e6c1d4b09b7d5a8798be288ea5f"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCyirtYOQxLjG9Z
Y1aFUzsIiukI/vlZAcs2mbOIH6TsHYDdfU6wX3A5mHCjTLeQ2/8rrdI7DQ4bDFXM
WR6Qfc5CyUqoacp0/Jbm2JAR5lFQu4+f9oaYrNjKWTsZTajNkYXahCb4X9JbTVp9
pepkZ3g20yVDF6SaX6484EC9IX0D1xtrrcPqHsyPE40Lw6JQYiGBNz+6J80K6NFC
ktA2xJr9zEDwgWk3D1xOM8Cfv4zteAylB57bkux/GhjxEzdFWfPBEehjfkbLQv6u
lZpIqg5pDWQkc+o41Psd0nqipOHum1i8/Qpr43hQlCXbPWvlL07sbkI7xZd/sOAa
2ACjAWJnAgMBAAECggEADZh33Kd3crdOcVmZqIxmdeeSCD/WP/tdfJpmq+pw9hPn
ELaui8qwsooTpbO9VLgT7cEOPbXoSZH+ZJGyvKD/2GEYoMtxgcgMO6bpDZvivEmU
DcPJiw26cmoqEGqz/Hdk4HdoukgdrhstVV0RhLTGWDJq53mA7Mp1a6hN9bj7mpOh
jzh3tTzF7qeTOIgJL/ej+sGr11HrVT37/51fTTUA2nFXx1LGmvvpGiFmYNo9OmL8
/W54SDX1sV3jWpSsrcKWp6bPW3EGX9uMGk2h+KY12qYKw1WwD+Io70xR4bJzRjrd
7XwgV0q37qcQ8Ci5mGWhuz5ZtJH85d4EDh3m+Q0OuQKBgQDp8PcnnlsOSSJle1eQ
xY1pQJnrmBALyQsLGOHXAqGGse6/Q4c0fWfNeMF5E13w8cul9l0vyo2+G7H5SqO2
XQ8aCS29UTBXf9oYfi6lQckrKZ8b8W4Xn4tB7wCriahkX4udQtgjVu3gAvtDxFLR
SLdGtiRJ4uJrs6NAYwhDtWUGDwKBgQDDYH+51TEGF+bz5vKi3iwos6Qyjzb8unnc
I4Q/ERXQ18twQG3cGHOQRJuf8lQ3bwEzv35OnJAF0idf+o/b4wVLoz7wTB9q2b0U
kdRi3a1ihiZQ86xDN/2vKAkFf2kJkOaijd2BahwvTcbd3x8/bHfsQudnlv+rH/Rj
uATThu/2KQKBgF4flVFbZUdaJXyvI4wb78lpNISVqd8UBF1ypWrcpCCNdoF9qeh0
jE8fRrhwElve7RDZDqUr2dujSPgED9pPlsPi7YQ+JjUOO7GfEyVqUoYLOPkFKkZW
6rCceKiLujSoPIQJYOzXDN4UVQPu+WM63oKUxgT0RCURIZ3GOo0DbqIBAoGBAKfc
WgDcxXD5ykkVzLPX9NLHfTSfTVwYDyjvLulMkZTMQxLfmEP4khmKiLcEagzyh3Lh
fPCnnSoTJBdXXJBMXblduW6VyIxyJPzuSi7jTNuQbI0yvndGPORnnlCl5iX849sX
zg8pjqupxEnOMLe6RtKrrMuYtXNeUgf3C9Z9Yd/5AoGBAOmqHblOKi34UfYauZP6
qhXVEBZaGVinvGHKhWdAMk9Y1HxS2inAbimYM2u6PbrqK8VBT3YpjhXuRKfJusDA
5kE0kIsBF3tk7ss5MQyH6PFBZrXf6164ysQW4n4fbmlavxL3sfMDTpk6lwRfJWDG
j/dpZ4yqEFUloz+03AyayUEZ
-----END PRIVATE KEY-----"""
client_email = "streamlit-dock-audit@adta5240f248wjgt.iam.gserviceaccount.com"
client_id = "105601661484535743000"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-dock-audit%40adta5240f248wjgt.iam.gserviceaccount.com"
universe_domain = "googleapis.com"



[SHEETS]
SHEET_ID = "https://docs.google.com/spreadsheets/d/1Jca0ZJYOQlq6ZJ62JO7FLXrMZwJMFPktomFf2QfA5tI/edit?gid=0#gid=0"
TAB_NAME = "Sheet1"
